### ISSUE TITLE
10.1 - les attributs height et width sont autorisés sur les éléments <img> et <svg>

### ISSUE THREAD

**Issue by JOP-Temesis** [arneoio/rgaa-checker#1]
Bonjour vous avez un faux positif sur votre outil concernant le 10.1 

Bien à vous, 

/J

**Comment by okeul** [comment]
Exemple sur https://www.temesis.com/
![Capture d’écran 2024-03-01 à 12 30 55](https://github.com/arneoio/rgaa-checker/assets/6248074/b61790fb-c4bf-4b78-a878-ad2c489e53aa)

**Comment by ponceto** [comment]
Merci pour le retour. Nous allons regarder ce bug report

**Comment by jonathan-vallet** [comment]
Bonjour,

En analysant la page plus en détail avec les règles appliquées pour le critère ce ne sont pas les images le soucis.
Pour l'attribut width on a le sélecteur `document.querySelectorAll('[width]:not(img, object, canvas, embed, svg)');` qui n'a pas renvoyé d'erreur sur les svg et img avec l'attribut width.
La seule non-conformité détectée vient de l'attribut [color] d'une balise <link>

Pour voir plus en détail les éléments qui sont en erreur d'un critère pour le moment ils sont indiqués dans la console.

<img width="315" alt="image" src="https://github.com/arneoio/rgaa-checker/assets/5329099/043bb4de-8659-43c5-b59a-d0650418f128">

**Comment by okeul** [comment]
@jonathan-vallet À ma connaissance il n'y a pas d'impact accessibilité sur la présence de cet attribut sur un élément <link>. Il ne s'agit pas d'une non conformité au regard du 10.1. D'ailleurs les autres outils de test auto comme axe-core ou wave (qui certes se basent sur WCAG) ne remontent pas ce type d'erreur. Vous devriez restreindre ce test au <body> uniquement.

**Comment by jonathan-vallet** [comment]
Je crois que les mots des balises ne sont pas affichés dans ton message. 
L'attribut color est effectivement interdit pour la présentation mais dans votre cas il est sur une balise "link" qui de toutes façons n'est pas visible dans la page vu qu'on est dans le <head>.

L'idée serait de restreindre la vérification du critère pour les éléments du <body> uniquement?

**Comment by okeul** [comment]
Je viens d'éditer le précédent message. Oui pas d'impact a11y sur ce type d'attribut dans le `<head>`. Il faudrait restreindre le test au `<body>`.

**Comment by jonathan-vallet** [comment]
Le retour a été pris en compte, les tests pour ce critère sont restreints au `<body>`.
[](https://github.com/arneoio/rgaa-checker/commit/ed4eba26c33364a51f127ca360dcbaf4a3edb8cd)

ça sera déployé sur la prochaine version. J'ai fait un tour des autres critères traités, les autres portant sur des tags et pas des attributs, on ne devrait pas avoir de conflit sur les éléments du `<head>`.
