### ISSUE TITLE
Bug sur le calcul de conformité

### ISSUE THREAD

**Issue by sbonaventure** [arneoio/rgaa-checker#3]
Le taux de conformité affiché semble bugué, en effet sur cet exemple le taux de conformité affiche est de 84%, alors que si on réalise l'export, on a 5 critères conformes pour 4 critères non conformité (soit 9 critères applicable).

Donc le taux de conformité devrait être de 55% (5/9) sur le périmètre applicable.

![image](https://github.com/arneoio/rgaa-checker/assets/5540566/27fd6716-7170-4f60-a6d8-f1f171960166)

**Comment by jonathan-vallet** [comment]
Pour le taux de conformité on considère en positif les "non applicable". On fait `(C + NA) / NC` pour avoir le pourcentage de "score". Les non traités ne font pas partie du résultat. La méthode de calcul est bien sûre ouverte à discussion.
Mais il faudrait effectivement qu'on précise via une tooltip comment ce calcul est fait.

**Comment by jonathan-vallet** [comment]
Nous allons faire la correction pour avoir juste `C / NC` et ne plus prendre en compte les critères non applicables.
