### ISSUE TITLE
Affichage du score de conformité

### ISSUE THREAD

**Issue by sbonaventure** [arneoio/rgaa-checker#4]
Sur la page correspondant à la capture 81 des 106 des critères ne sont pas testés, il me parait discutable d'affiche le % de conformité de cette manière, car des personnes non avertis pourraient prendre ce taux comme un valeur absolue sans voir (ou vouloir voir) qu'un certain nombre de critères ne sont pas testés.

Il semblerait préférable de faire une indication plus respectueuse du taux de conformité tel que demandé par le cadre réglementaire du RGAA. Par exemple :

tx de conformité|condition|
|---|--- |
56% | si l'ensemble des critères NT deviennent NA |
6% | si l'ensemble des critères NT deviennent NC |
96% | si l'ensemble des critères NT deviennent C

![image](https://github.com/arneoio/rgaa-checker/assets/5540566/68a06f7c-fb38-4afb-bc6a-ebaa45b5fa02)

**Comment by sbonaventure** [comment]
Pour information, c'est une expérience vécue récemment lors d'un échange avec une agence web, il m'a été indiqué qu'une de leur production était conforme à 80% au RGAA, et que cette information était fourni par cet outil...

**Comment by twogrey** [comment]
J'étais justement en train d'écrire une issue précisément à ce sujet. 
Du coup, je me contente d'appuyer le raisonnement de Simon via ce commentaire ☺️

**Comment by jonathan-vallet** [comment]
Comme indiqué dans l'autre "issue", on va revoir le calcul pour faire `Conforme / Non Conforme`. Les NA sont aujourd'hui dans le calcul. On tomberait donc dans l'exemple à 56%.
Mais pour le pourcentage je suis d'accord. Même avec 100% de conformes sur ceux qui sont validés automatiquement ça ne garanti absolument pas la conformité des autres avec autant de critères NT. Il faut surtout qu'on indique quelque part dans le score qu'ils ne sont pas pris en considération et que le score n'est pas représentatif de la conformité globale. 

On pourrait ajouter une mention sous le score, par exemple:
Score:
56%
**pour 32 critères traités sur 106**

Est-ce que cela répondrait à la problématique? Le score se mettant à jour quand on change l'état des critères, à terme il devrait être plus pertinent

**Comment by sbonaventure** [comment]
oui, tout a fait.

Après, c'est une question d'UI, l'objectif c'est d'éviter les mécompréhensions sur le niveau de conformité affiché qui ne doit pas être interprété comme la valeur absolue tant que tous les critères n'ont pas été évalués

**Comment by jonathan-vallet** [comment]
Pour la prochaine version le calcul a été revu, et pour éviter que le score ne soit pas représentatif, il ne s'affichera que quand tous les critères seront traités par une personne réalisant l'audit.

Nous reverrons sans doute l'UX/UI prochainement, mais ça sera déjà un quick fix qui évitera que des personnes pensent avoir un bon score alors que tous les critères qu'on pas été traités. L'outil a pour vocation d'aider les personnes à réaliser les audits, c'est contreproductif si des gens sans connaissance sur le sujet de l'accessibilité voient un score directement et surtout s'ils le pensent bon.

<img width="223" alt="Capture d'écran 2024-03-12 161707" src="https://github.com/arneoio/rgaa-checker/assets/5329099/d1c461a6-8a98-47aa-9287-575bd385e1c1">

<img width="219" alt="Capture d'écran 2024-03-12 161659" src="https://github.com/arneoio/rgaa-checker/assets/5329099/471d7a2f-41bd-4bb8-8af9-096352e4e7e6">
