### ISSUE TITLE
Ajouter les numéros de critères lors de l'export

### ISSUE THREAD

**Issue by sbonaventure** [arneoio/rgaa-checker#5]
La fonctionnalité d'export est très intéressante, cependant il me serait utile d'avoir à référence au numéros de critères correspondant dans l'export

**Comment by jonathan-vallet** [comment]
Pour l'instant l'export se base sur la grille d'audit fournie dans le kit "officiel", ça prend juste "état + message".
quel format aurais-tu souhaité plus précisément? ce serait pour exporter sur une grille custom ou pour visualiser autrement?

Je pense que la fonctionnalité est à réfléchir pour que ça soit paramétrable suivant les besoins de chacun. Dans la fenêtre de paramètres (qui n'existe pas encore) on pourrait avoir un input avec le format d'export et plusieurs variables qu'il sera possible d'inclure.

**Comment by sbonaventure** [comment]
J'aurais juste souhaité avec une colonne supplémentaire pour indiquer au regard de chaque ligne qui est C/NC/NA/NT a quel numéro de critère cela correspond
