### ISSUE TITLE
Test 10.1.2 : détection des balises <image> dans <svg>

### ISSUE THREAD

**Issue by nicozerr** [arneoio/rgaa-checker#7]
Bien que le RGAA n'en fasse pas mention dans la liste des balises autorisées à utiliser les attributs `width` et `height`, il existe une balise `<image>` ([voir la doc sur MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/image)) `<img>`, synonyme de la balise `<img>`, pouvant accueillir une image dans un `<svg>`.

J'attache à mon commentaire un exemple de fichier SVG contenant cette balise `<image>`:
![map](https://github.com/arneoio/rgaa-checker/assets/5611376/1237cebf-3420-4a39-b1c1-9ba7d7e44a0e)

Le test 10.1.2 indique une mauvaise utilisation des attributs `width` et `height` sur la balise `<image>`, alors que, comme les balises `<img>`, doivent être autorisées à utiliser ces attributs.

Je pense que l'extension ne devrait pas identifier cela comme une erreur.

**Comment by jonathan-vallet** [comment]
Merci pour le retour, nous allons ajouter la balise <image> dans celles qui sont autorisées. Même si ce n'est pas dans le glossaire du RGAA ça semble pertinent que ce soit valide.
Je pense qu'on fera une version avec le fix d'ici la fin de semaine prochaine suivant comment avance les nouvelles grosses features :)

**Comment by jonathan-vallet** [comment]
La prise en charge de la balise <image> dans es <svg> a été ajoutée dans la dernière version en ligne (0.24.0)
